### ISSUE TITLE
Player often not teleported to new HQ locations on loading of Persistent Save [SP]

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#180] opened 2017-12-24 16:10 UTC
I've noticed this recently - the further away your HQ is from the default start location when you load a Persistent Save, the more likely you are to not get teleported there and instead get teleported to the default base location south of Neri. 

So if your HQ is off somewhere on the other side of the map you'll almost never be teleported there and instead end up naked and alone in the middle of nowhere. Rude.

**Comment by IrLED** [comment] 2017-12-26 07:44
Duplicate of #140 
What version do you experience that behavior with?
That supposedly is fixed for about month already (see #137 #140)

**Comment by zverofaust** [comment] 2017-12-26 12:55
It's happened with _every_ version for about the past month including the latest. I forgot I wrote an issue about it already! Sorry!

**Comment by colmaniac** [comment] 2018-01-05 14:10
Yes im having that problem too, always starting at original start point, the only way to get back is to teleport back

**Comment by IrLED** [comment] 2018-01-05 14:39
@colmaniac 
I suppose you are referring to latest release.
After you appear in the game-world, are you teleported anywhere or just stay on the road at some distance from default camp place? If nothing like teleporting happens - that means save is not loaded at all (it's another issue)

**Comment by colmaniac** [comment] 2018-01-05 14:56
when I first started I moved my HQ to the far western point on map in the sw corner,  on saving and reloading it asks me to reload save, on reloading I start from where I very first started before I moved.
My HQ and Petros is still with me for a few seconds before disappearing to where I moved to, Im still left at the original place. This is in current build.  I have to use the fast travel to get back to HQ.

**Comment by StefArma** [comment] 2018-02-01 14:26
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/da9497ad36093d1555b162b1f422997b217692ac  i've added this sleep 2 sec-- it do the job 90% of times... it happened that i was multitasking and tabbed out reducing available cpu for arma causing i was teleported before the HQ position was moved to loaded location

**Comment by StefArma** [comment] 2018-02-15 18:08
I fixed by making the HQ pos as the first parameter of loadgame

**Closed by StefArma** 2018-02-15 18:08 UTC
