### ISSUE TITLE
MP mission parameters with force=1; can't be changed by admin on Linux DS.

### ISSUE THREAD

**Issue by Sparker95** [A3Antistasi/antistasiofficial#44] opened 2017-10-17 20:47 UTC
Description.ext (and also acesettings.hpp) have a Params class that contains parameters that can be accessed by admin from the lobby. All the options have a force attribute set to 1. As we have found in [this thread](http://www.a3antistasi.com/forum/m/38173738/viewthread/31070410-unable-to-start-new-campaign/post/132859874#p132859874), this attribute prevents a server admin from changing these options on linux dedicated server. However we have never experienced it on our Nitrado server.

**Comment by IrLED** [comment] 2017-10-18 04:56
@Sparker95 
I wrote to that thread. At the moment i suspect the presence of [-autoInit parameter](https://community.bistudio.com/wiki/Arma_3_Startup_Parameters). If it's the case, then params just take effect at the moment of mission start (no time for admin to react). Regarding the **force** attribute of mission parameter, i couldn't find any references to it in official wiki.

**Comment by IrLED** [comment] 2017-10-18 07:06
It's not the confirmed bug, moving issue to **research** status

**Comment by IrLED** [comment] 2017-10-18 14:04
Looks like **force =** along with **typeName =** might come from ACE (https://ace3mod.com/wiki/framework/settings-framework.html#1-how-do-they-work) and maybe misused

**Comment by IrLED** [comment] 2017-10-18 17:36
Apparently the reported issue was related to presence of **-autoInit** parameter. Closing the issue (at least for now)

**Closed by IrLED** 2017-10-18 17:36 UTC
Labels: research
